[package]
name = "spoofer"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rquest = { version = "=5.1.0", features = ["cookies", "json", "websocket"] }
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
